import { serviceLeadSections } from "./leads";
import type { GuideSection, RestaurantGuide } from "./restaurant";

export type ServiceIndustry = {
  id: string; name: string; noun: string; slug: string; insuranceSlug: string;
  intro: string; scope: string[]; costs: string[]; bidInputs: string[];
  localQuestions: string[]; insuranceQuestions: string[]; sections: GuideSection[];
};

export const SERVICE_INDUSTRIES: ServiceIndustry[] = [
  {
    id: "janitorial", name: "Janitorial", noun: "janitorial business", slug: "how-to-start-a-janitorial-business", insuranceSlug: "cleaning",
    intro: "Start a janitorial business by choosing a narrow type of account, building a repeatable scope of work, and pricing the labor needed to deliver it. Win an account you can staff reliably before buying equipment for services you have not sold.",
    scope: ["Choose offices, small retail, common areas, or another defined account type.", "Separate recurring visits from deep cleans, floor work, and specialist services.", "Set a service radius and the hours you can reliably staff."],
    costs: ["Cleaning equipment and initial supplies", "Vehicle or transport setup", "Business setup, insurance deposits, and any required registration", "Uniforms, training, and payroll before customer payment", "Scheduling, quoting, and bookkeeping tools"],
    bidInputs: ["Visits per month and estimated labor hours per visit", "Loaded hourly labor cost, including paid noncleaning time", "Consumables you supply versus those the customer supplies", "Travel, supervisor checks, equipment wear, and rework allowance"],
    localQuestions: ["Does the state or locality require janitorial employer or property-services registration?", "Are the cleaning services you will sell subject to sales tax?", "What rules apply to chemical storage, wastewater disposal, and the chosen premises?", "Would adding pest control, biohazard cleanup, or exterior work change the licensing inquiry?"],
    insuranceQuestions: ["Damage to customer property and exclusions for property in your care", "Lost keys, employee dishonesty, and any requested janitorial bond", "Workers' compensation, business driving, and equipment", "Client certificate and additional insured requests"],
    sections: [
      { id: "choose-accounts", title: "Choose a service you can repeat well", paragraphs: ["Define the first account you want: its type, size, location, service hours, and tasks. Office cleaning after hours is a different operating model from cleaning a busy retail space during trading hours. Keep your first offer specific enough to estimate and supervise.", "Write down the work you will not include in the base visit. Floor stripping, exterior windows, pressure washing, kitchen exhaust cleaning, and hazardous cleanup can need different equipment, skills, or insurance. Quote an additional service only after checking that you can perform it properly."] },
      { id: "walkthrough", title: "Turn the walkthrough into a written scope", paragraphs: ["Ask the customer to show you every area, explain access and alarm procedures, and identify who supplies consumables. Record flooring, restrooms, waste collection, occupied hours, and any surfaces requiring special care. Get permission before taking photographs.", "Build a task-and-frequency schedule instead of promising to keep everything clean. Identify the person who can approve extras, report a missed task, and sign off on service. Include how keys and access credentials are issued and returned."] },
      { id: "price", title: "Price labor, supervision, and payment delays", paragraphs: ["Estimate hours per visit, multiply by the planned visits, and add paid travel or setup time. Include payroll costs, supplies, equipment wear, supervision, and a share of overhead. Compare the resulting price with what the account will actually pay before hiring a crew.", "A recurring contract can still strain cash if payroll is weekly and the customer pays later. Model the time from the first visit to the first collected invoice. Keep deep cleaning and supply restocking visible as separate items if they are outside the base scope."] },
      { id: "setup", title: "Confirm registration and prepare the crew", paragraphs: ["Business formation and permission to provide a particular service are separate questions. Use the state guide below to identify official resources, then confirm local business licensing, tax treatment, and employer requirements for the actual operation.", "Prepare a training plan, a site access procedure, and a way to report damaged property or unsafe conditions. Review product labels and safety data with a qualified supervisor. OSHA publishes specific guidance for employers using cleaning chemicals."], links: [{ label: "OSHA: protecting workers using cleaning chemicals", href: "https://www.osha.gov/sites/default/files/publications/OSHA3512.pdf" }] },
      { id: "first-account", title: "Win and retain the first account", paragraphs: ["Create a short proposal with the task schedule, visit frequency, price, payment terms, excluded services, and an issue-reporting contact. Have appropriate contract language reviewed before use. Provide references or permission-cleared work examples; do not invent testimonials to fill a new website.", "Start with a manageable local prospect list and a clear offer to perform a walkthrough. After the first service, compare estimated hours with actual hours and correct the scope or price before repeating the mistake across more accounts. Track retained monthly revenue and margin, not just the count of signed contracts."] },
    ],
  },
  {
    id: "pool-construction", name: "Pool construction", noun: "pool construction business", slug: "how-to-start-a-pool-construction-business", insuranceSlug: "pool",
    intro: "A pool construction business needs a defined construction scope, the right licensing path, dependable specialist subcontractors, and enough cash to carry a project between payment milestones. Start by planning one complete project before quoting several at once.",
    scope: ["Choose new installations, renovation, or a defined portion of construction.", "Separate structural work from electrical, plumbing, decking, and maintenance.", "Identify which tasks employees perform and which qualified subcontractors handle."],
    costs: ["Licensing preparation, professional fees, and deposits", "Survey, design, engineering, and estimating support", "Vehicle, tools, and rented excavation equipment", "Initial materials and subcontractor mobilization", "Working cash between project milestones"],
    bidInputs: ["Site access, soil assumptions, excavation and spoil removal", "Shell, plumbing, electrical, finishes, and deck scope", "Engineering, permits, inspections, and subcontractor pricing", "Progress-payment timing, warranty work, and contingency"],
    localQuestions: ["Which pool-construction classification and qualifying-person credentials apply?", "Who can perform and permit electrical, plumbing, and gas work?", "Which zoning, setbacks, barriers, drainage, and inspections apply to this site?", "Does a public or commercial pool need health-department review in addition to building approval?"],
    insuranceQuestions: ["Excavation and structural pool construction in the insured description", "Subcontracted work and completed-operations coverage", "Damage to existing property, underground services, and exclusions", "Workers, vehicles, rented equipment, and project-specific requirements"],
    sections: [
      { id: "model", title: "Choose the construction model before the equipment", paragraphs: ["Define whether you will sell an entire pool project or perform a specific trade for another builder. Identify the pool types and finish systems your team can deliver. Pool cleaning and maintenance are different services and should not stand in for construction experience in a proposal or insurance application.", "Create a responsibility map for design, excavation, shell, plumbing, electrical work, decking, and commissioning. Name the specialist you expect to use for each part and verify that the intended subcontracting arrangement fits local licensing rules."] },
      { id: "licensing", title: "Match credentials to the actual project", paragraphs: ["Use the state guide to find the contractor licensing authority. Describe the work in plain terms rather than asking only whether a general contractor license is enough. Confirm the classification, qualifying-person requirements, and work reserved to other licensed trades.", "Ask the local building office about the site-specific approval sequence. A contractor credential and a project's permit are different things. Public or commercial pool work can involve additional review, so define the customer and intended use before accepting the contract."] },
      { id: "estimate", title: "Build a complete first-project estimate", paragraphs: ["Start with the site rather than a standard price per pool. Record access, demolition, excavation, spoil removal, utility conflicts, material delivery, and the restoration promised after construction. Obtain specialist estimates against the same drawing and scope version.", "Separate confirmed allowances from unknown conditions. Spell out what changes the price and how a change order is authorized. Model customer receipts and supplier payments by milestone so a profitable estimate does not conceal a period when you cannot fund the work."] },
      { id: "operations", title: "Prepare a safe, inspectable construction sequence", paragraphs: ["Assign responsibility for site security, inspection booking, equipment access, and subcontractor coordination. Plan which work cannot proceed until an inspection or another trade is complete. Use qualified people to prepare excavation and other safety arrangements; a startup checklist is not a construction method.", "OSHA's excavation resources are a starting point for the employer's safety planning. Document the site-specific process with the people responsible for performing and supervising the work."], links: [{ label: "OSHA: trenching and excavation resources", href: "https://www.osha.gov/trenching-excavation" }] },
      { id: "sell", title: "Sell a clear scope and finish with a handoff", paragraphs: ["Show prospective customers relevant, permission-cleared completed work and describe what your estimate includes. Build relationships with designers, landscapers, and other local project professionals without promising dates you have not checked against capacity and approvals.", "Close the project with the agreed inspection records, equipment documentation, customer orientation, and a written list of remaining items. Compare estimated and actual costs by construction phase so the next bid reflects what you learned."] },
    ],
  },
  {
    id: "roofing", name: "Roofing", noun: "roofing business", slug: "how-to-start-a-roofing-business", insuranceSlug: "roofer",
    intro: "Start a roofing business with a defined roof system and customer type, a qualified crew, a workable safety program, and a bid that covers labor, materials, disposal, overhead, and callbacks. Confirm your licensing and insurance scope before advertising or accepting work.",
    scope: ["Choose residential or commercial work and the roof systems you will install.", "Distinguish repairs, replacement, new construction, and specialty methods.", "Set limits on height, pitch, access, and jobs requiring outside specialists."],
    costs: ["Licensing, exams, training, and insurance deposits", "Vehicle, tools, access equipment, and protective systems", "Material and disposal deposits", "Crew payroll, supervision, and scheduling", "Cash for weather delays and callbacks"],
    bidInputs: ["Measured roof scope, access, tear-off, and disposal", "Material specifications, delivery, and waste allowance", "Labor, supervision, safety setup, and equipment", "Decking assumptions, approved extras, and customer payment dates"],
    localQuestions: ["Is a roofing-specific license or registration required?", "Are residential and commercial roofing treated differently?", "Which local permits, inspections, and contractor credentials apply?", "What consumer-contract and advertising rules govern the work you will sell?"],
    insuranceQuestions: ["Roofing operations, roof types, maximum height, and subcontracting", "Open-roof water damage, hot work, and relevant exclusions", "Workers' compensation and crew classification", "Completed operations, business vehicles, tools, and customer requirements"],
    sections: [
      { id: "specialty", title: "Choose a roofing specialty you can deliver", paragraphs: ["List the systems, building types, and project sizes you can complete with your team. Define the repair and replacement work you will accept and the work you will refer elsewhere. A broad advertising promise can create obligations your crew and insurance were never prepared to handle.", "Write a simple acceptance checklist for access, height, pitch, roof condition, and occupied-building constraints. Arrange specialist support before selling a project that depends on it. Keep supervision and quality control in the operating plan even when installation is subcontracted."] },
      { id: "credentials", title: "Resolve licensing before marketing", paragraphs: ["Roofing has its own licensing or registration route in some states, even where other general construction is handled locally. Check the state guide below and the building department for the job address. Ask separately about commercial work, subcontracting, and required business identifiers in advertising.", "Prepare the exact operations description for your broker, including roof systems, heights, payroll, and subcontractor use. Ask the broker to review exclusions and any customer requirements against the proposed policy. Do not describe roofing as general handyman work to get a simpler quote."] },
      { id: "bid", title: "Price a complete job, including the uncertain parts", paragraphs: ["Build the estimate from measured work, material specifications, access, tear-off, disposal, labor, and safety setup. Record assumptions about hidden damage and specify the process for authorizing extra work. Compare supplier quotes using the same material list and delivery requirements.", "Add a share of office costs, selling time, warranty work, and supervision. Distinguish markup on cost from margin on revenue. Schedule cash receipts against material orders and payroll; a deposit is not automatically profit available to spend on another project."] },
      { id: "crew", title: "Prepare the crew and site process", paragraphs: ["A roofing startup needs qualified safety planning as well as installation skill. Assign responsibility for site assessment, fall protection, access, public protection, weather decisions, and emergency procedures. Have the responsible competent people review the actual project conditions.", "Use OSHA's roofing and fall-prevention resources as references when preparing the employer's safety program. A brief startup guide cannot specify a safe work method for every roof."], links: [{ label: "OSHA: reducing falls during re-roofing", href: "https://www.osha.gov/sites/default/files/publications/reducing-falls-during-residential-construction-re-roofing.pdf" }] },
      { id: "reputation", title: "Build a local record of completed work", paragraphs: ["Present a written proposal with the system, scope, exclusions, payment milestones, and cleanup responsibilities. Use clear photographs and customer-approved project examples as the portfolio grows. Have the contract reviewed for the applicable consumer rules.", "After each job, compare estimated labor and materials with actual use, document the final walkthrough, and track callbacks. A smaller number of well-managed projects can provide better evidence for future customers than accepting every inquiry and losing control of the schedule."] },
    ],
  },
  {
    id: "tree-service", name: "Tree services", noun: "tree service business", slug: "how-to-start-a-tree-service-business", insuranceSlug: "tree-service",
    intro: "Start a tree service business by defining the work your team is qualified to perform, verifying local and state credentials, and building a site-assessment and estimating process. Equipment ownership alone is not evidence that a business is ready for complex removals or utility work.",
    scope: ["Separate pruning, removal, stump work, plant health care, and utility work.", "Define which jobs require specialist crews, cranes, or outside advice.", "Set a service area and a clear process for declining work outside your capability."],
    costs: ["Qualifications, training, licenses, and insurance deposits", "Vehicle, trailer, tools, and maintained safety equipment", "Rented or owned chipping and stump equipment", "Disposal, storage premises, and maintenance", "Payroll reserve and specialist subcontractor deposits"],
    bidInputs: ["Site access, tree condition, targets, and work boundaries", "Crew time, supervision, specialist equipment, and haulage", "Debris ownership, disposal, stump work, and site restoration", "Permits, customer permissions, and weather-related rescheduling"],
    localQuestions: ["Does the state require an arborist, tree-expert, or tree-business credential?", "Are protected-tree removal or municipal tree permits involved?", "Do pesticide applications need separate business or applicator credentials?", "Does work near utilities require a different qualification and operating arrangement?"],
    insuranceQuestions: ["Pruning, removal, stump grinding, and plant-health services actually offered", "Maximum working height, climbing, crane use, and utility exclusions", "Subcontractors, employees, vehicles, and equipment", "Property damage, completed operations, and contract requirements"],
    sections: [
      { id: "services", title: "Define the work and its limits", paragraphs: ["Describe each service separately: pruning, tree removal, stump grinding, inspections or advice, plant health care, and utility-line work. List the training, credentials, supervision, and equipment needed for each. Start with the services your team can reliably perform.", "Write down situations that require a specialist or a declined job. Customer urgency does not make an unfamiliar removal appropriate for the crew. Do not advertise utility or chemical-treatment services simply because they sound adjacent to ordinary tree care."] },
      { id: "licenses", title: "Check tree-specific credentials", paragraphs: ["Several states regulate arborists or tree-care businesses separately from general contractors. Use the state resources below, then ask the local authority about protected trees, public trees, and removal permits. Business registration does not establish permission to perform every tree service.", "If you intend to apply pesticides or provide plant-health treatments, check the relevant pesticide licensing separately. Keep copies of current credentials and define which qualified person is responsible for the work you advertise."] },
      { id: "estimate", title: "Estimate the entire site operation", paragraphs: ["Visit the site before producing a firm scope. Record access, structures and property to protect, disposal arrangements, the work boundary, and the customer's expectations for cleanup. Identify who is authorized to approve work and whether additional permissions are needed.", "Include crew time, supervision, travel, maintenance, disposal, equipment rental, and restoration promised to the owner. Clearly separate stump grinding or debris hauling if they are optional. Schedule specialist equipment only after confirming that the job and permissions are ready."] },
      { id: "safety", title: "Build qualified supervision into the business", paragraphs: ["Assign responsibility for assessing the site, briefing the crew, maintaining equipment, and coordinating emergency response. Use qualified people to develop the methods and training for the actual operations. A business-startup article is not a cutting, climbing, or rigging instruction.", "OSHA's tree-care standards page identifies the applicable safety resources and the role of state plans. Use it as a reference when building an employer program with the people who supervise the work."], links: [{ label: "OSHA: tree-care industry standards", href: "https://www.osha.gov/tree-care/standards" }] },
      { id: "customers", title: "Earn referrals with a clear scope and clean handoff", paragraphs: ["Prepare a proposal that identifies the trees and work, customer permissions, access, cleanup, price, and payment terms. Photograph the agreed scope with permission. Have the contract reviewed before using it as a standard form.", "Build local relationships with property managers, landscapers, and homeowners whose needs match your capabilities. After completion, document the handoff, ask for feedback, and compare the estimate with actual time and equipment use. Track repeat work and callbacks as the business grows."] },
    ],
  },
  {
    id: "remodeling", name: "Remodeling", noun: "remodeling business", slug: "how-to-start-a-remodeling-business", insuranceSlug: "remodeler",
    intro: "Start a remodeling business with a narrow project type, a clear licensing scope, reliable specialty trades, and a written process for estimates and changes. Plan the first project from site visit to final walkthrough before filling the calendar with overlapping jobs.",
    scope: ["Choose kitchens, bathrooms, interiors, or another defined project category.", "Separate cosmetic work from structural, electrical, plumbing, and mechanical work.", "Define the project size and occupied-home conditions your team can manage."],
    costs: ["Licensing, training, professional help, and insurance deposits", "Vehicle, tools, dust-control and protective equipment", "Estimating, bookkeeping, and project coordination", "Initial materials and subcontractor deposits", "Payroll and cash for delayed milestones or callbacks"],
    bidInputs: ["Demolition, installation, finish, and cleanup scope", "Labor, subcontractor quotes, materials, and delivery", "Allowance selections and assumptions about concealed conditions", "Permits, customer changes, payment milestones, and warranty reserve"],
    localQuestions: ["Does residential remodeling require a contractor license, registration, or qualifying person?", "Which tasks need separately licensed electrical, plumbing, or mechanical trades?", "What permit and inspection sequence applies to the project address?", "Do the building age and work trigger lead-safe renovation or other hazardous-material requirements?"],
    insuranceQuestions: ["Actual remodeling scope, structural work, and occupied premises", "Subcontracted work and completed operations", "Damage to existing property and relevant exclusions", "Employees, business vehicles, tools, and customer certificate requests"],
    sections: [
      { id: "focus", title: "Choose a repeatable first project type", paragraphs: ["Define the room, finish level, project size, and customer type you want to serve. Small bathroom renovations and whole-home structural projects require different teams, capital, and supervision. Choose a scope you can estimate from experience and inspect consistently.", "Map the work you self-perform and the work reserved for specialist trades. Confirm those boundaries with the licensing authority rather than assuming a general business registration covers everything. Find dependable subcontractors before selling projects that rely on them."] },
      { id: "site-visit", title: "Use the site visit to expose assumptions", paragraphs: ["Record existing conditions, access, protection of occupied spaces, delivery and waste arrangements, and the customer's decisions still outstanding. Ask who approves changes and which hours the site is available. Get permission to document the space.", "Put allowances and exclusions in writing. A price for an unfinished selection is an allowance, not a promise that every product will fit the budget. Define how concealed damage, customer changes, and delayed selections will affect the scope and schedule."] },
      { id: "credentials", title: "Check contractor and renovation requirements", paragraphs: ["Use the state guide to identify contractor licensing or registration resources and confirm the local permit sequence. Have a legal adviser review the customer contract, payment milestones, and required disclosures before using it on the first job.", "EPA's Renovation, Repair and Painting program applies to covered paint-disturbing work in pre-1978 housing and child-occupied facilities. Check firm and individual certification requirements, any applicable exemptions, and whether an authorized state administers the program before advertising covered work."], links: [{ label: "EPA: RRP guidance for contractors", href: "https://www.epa.gov/lead/renovation-repair-and-painting-program-contractors" }] },
      { id: "cash", title: "Plan cash alongside the construction schedule", paragraphs: ["Estimate materials, labor, subcontractors, permits, waste, supervision, and overhead. Align ordering and payroll with the actual customer payment schedule. Do not use money needed to finish one job as the assumed funding for another.", "Create a change-order process with description, price, schedule effect, and written authorization. Review job costs each week against the estimate. The price must leave room for project management, callbacks, and the selling time that is not visible on the jobsite."] },
      { id: "handoff", title: "Create a portfolio from completed projects", paragraphs: ["Start with projects suited to your team and build permission-cleared before-and-after examples. Explain the scope and decisions behind the work, not just the finished photograph. Ask satisfied customers for honest feedback without inventing reviews or outcomes.", "Close each project with the agreed inspections, a punch list, product documentation, and a final walkthrough. Record unresolved items and who owns them. Compare actual costs and changes with the original estimate before quoting the next similar project."] },
    ],
  },
];

export function nationalServiceGuide(industry: ServiceIndustry): RestaurantGuide {
  return {
    slug: industry.slug, title: `How to start a ${industry.noun}: a practical launch plan`,
    description: `Plan a ${industry.noun} with a defined service scope, startup costs, pricing, licenses, insurance questions, and a first-customer checklist.`,
    intro: industry.intro, category: "Service business startup", industry: industry.name,
    insurancePath: `/insurance/${industry.insuranceSlug}`, quoteKind: "service", tradeLabel: industry.name,
    nationalSlug: industry.slug,
    sections: [
      ...industry.sections,
      ...serviceLeadSections(industry),
      { id: "startup-costs", title: "Build your startup budget", paragraphs: ["Price the essentials for the first contracts you can deliver, then add the cash needed until customers pay. Get supplier estimates before committing to equipment. Keep one-time spending separate from monthly costs and do not treat pending financing as available cash."], checklist: industry.costs },
      { id: "insurance", title: "Prepare for an insurance conversation", paragraphs: ["Give the broker an accurate service description, work locations, staffing and subcontracting plan, equipment information, and any customer insurance clauses. Discuss these items before accepting an obligation you cannot meet. Coverage availability depends on the operation, state, and insurer."], checklist: industry.insuranceQuestions, links: [{ label: `${industry.name} insurance coverage`, href: `/insurance/${industry.insuranceSlug}` }] },
    ],
  };
}
