export const TRADES: {label:string;value:string}[] = [
  { label: "General contractor", value: "General contractor" },
  { label: "Remodeling / renovations", value: "Remodeling / renovations" },
  { label: "Roofing", value: "Roofing" },
  { label: "HVAC / heating and air conditioning", value: "HVAC / heating and air conditioning" },
  { label: "Plumbing", value: "Plumbing" },
  { label: "Electrical", value: "Electrical" },
  { label: "Painting", value: "Painting" },
  { label: "Carpentry / framing", value: "Carpentry / framing" },
  { label: "Masonry / concrete", value: "Masonry / concrete" },
  { label: "Siding / gutters", value: "Siding / gutters" },
  { label: "Flooring / tile", value: "Flooring / tile" },
  { label: "Excavation / grading / site work", value: "Excavation / grading / site work" },
  { label: "Demolition", value: "Demolition" },
  { label: "Deck construction", value: "Deck construction" },
  { label: "Fence installation / repair", value: "Fence installation / repair" },
  { label: "Paving / asphalt", value: "Paving / asphalt" },
  { label: "Tree service", value: "Tree service" },
  { label: "Restoration (water / fire damage)", value: "Restoration (water / fire damage)" },
  { label: "Waterproofing", value: "Waterproofing" },
  { label: "Foundation repair / underpinning", value: "Foundation repair / underpinning" },
  { label: "Pool construction / service", value: "Pool construction / service" },
  { label: "Welding / metal fabrication", value: "Welding / metal fabrication" },
  { label: "Other trade", value: "Other trade" },
];
